# このファイルをpyproject.tomlに変更してuv syncでインストール。uv run aiocr.pyで実行
[project]
name = "aiocr"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "accelerate==1.12.0",
    "gradio==6.6.0",
    "pypdfium2==5.5.0",
    "torch==2.10.0",
    "torchvision==0.25.0",
    "transformers==5.2.0",
]

[tool.uv.sources]
torch = [{index = "torch"}]
torchvision = [{index = "torch"}]

[[tool.uv.index]]
name = "torch"
url = "https://download.pytorch.org/whl/cu130"
